version: "3.9"
name: "digital school"

services:
    api-gateway:
        build: ./services/api-gateway
        depends_on:
            - discovery-service
        ports:
            - "8000:8080"
        environment:
            - EUREKA_HOST=discovery-service
            - CORS_ALLOW_ORIGIN=${CORS_ALLOW_ORIGIN}
    school-management:
        build: ./services/school-management
        depends_on:
            - postgres
            - discovery-service
        ports:
            - 8080
        environment:
            - PG_DB=${PG_DB}
            - PG_PASSWORD=${PG_PASSWORD}
            - PG_USER=${PG_USER}
            - CORS_ALLOW_ORIGIN=${CORS_ALLOW_ORIGIN}
            - PG_HOST=postgres
            - EUREKA_HOST=discovery-service
    social-service:
        build: ./services/social-service
        depends_on:
            - postgres
            - discovery-service
        ports:
            - 8080
        environment:
            - PG_DB=${PG_DB}
            - PG_PASSWORD=${PG_PASSWORD}
            - PG_USER=${PG_USER}
            - CORS_ALLOW_ORIGIN=${CORS_ALLOW_ORIGIN}
            - PG_HOST=postgres
            - EUREKA_HOST=discovery-service
    auth-service:
        build: ./services/authentication-service
        depends_on:
            - postgres
            - discovery-service
        ports:
            - 8080
        environment:
            - PG_DB=${PG_DB}
            - PG_PASSWORD=${PG_PASSWORD}
            - PG_USER=${PG_USER}
            - MAIL_SMTP_HOST=${MAIL_SMTP_HOST}
            - MAIL_SMTP_PORT=${MAIL_SMTP_PORT}
            - MAIL_SMTP_USER=${MAIL_SMTP_USER}
            - MAIL_SMTP_FROM=${MAIL_SMTP_FROM}
            - MAIL_SMTP_PASSWORD=${MAIL_SMTP_PASSWORD}
            - JWT_SECRET=${JWT_SECRET}
            - CORS_ALLOW_ORIGIN=${CORS_ALLOW_ORIGIN}
            - PG_HOST=postgres
            - EUREKA_HOST=discovery-service
    discovery-service :
        build: ./services/discovery-service
        ports:
          - "8761:8761"
    worldcities:
        build : ./worldcities
        depends_on:
            - postgres
        environment:
            - PG_DB=${PG_DB}
            - PG_PASSWORD=${PG_PASSWORD}
            - PG_USER=${PG_USER}
            - PG_PORT=5432
            - PG_HOST=postgres
    postgres:
        build: ./postgres
        environment:
            - POSTGRES_DB=${PG_DB}
            - POSTGRES_PASSWORD=${PG_PASSWORD}
            - POSTGRES_USER=${PG_USER}
        ports:
            - "5432:5432"
        volumes:
            - db_cluster:/var/lib/postgresql/data

volumes:
    db_cluster: {}